// Original prompts curated for medium difficulty; calibrate through playtesting.
// General knowledge and specialist categories have equal-sized pools.
// Stable facts and dated sports questions avoid changing records. See docs/question-bank.md.
const rows = [
  ["Space","What is Saturn's largest moon?","Titan"],
  ["Space","Which moon of Jupiter is the largest moon in the solar system?","Ganymede"],
  ["Space","Which NASA probe became the first spacecraft to enter interstellar space in 2012?","Voyager 1","Voyager One"],
  ["Space","Which space telescope, launched in 1990, is named after an astronomer who studied expanding galaxies?","Hubble","Hubble Space Telescope"],
  ["Space","Which major galaxy is predicted to collide with the Milky Way?","Andromeda","Andromeda Galaxy","M31"],
  ["Space","Which planet was discovered in 1846 after its position was predicted mathematically?","Neptune"],
  ["Space","What classification did the International Astronomical Union give Pluto in 2006?","dwarf planet","a dwarf planet"],
  ["Space","Which planet, named after the Roman goddess of love, has a rotation period longer than its year?","Venus"],
  ["Geography","Which strait separates southern Spain from northern Morocco?","Strait of Gibraltar","Gibraltar Strait","Gibraltar"],
  ["Geography","Which continent has the most sovereign countries?","Africa"],
  ["Geography","Which river flows through both Vienna and Budapest?","Danube","the Danube","Danube River"],
  ["Geography","Name either of South America's two landlocked countries.","Bolivia","Paraguay"],
  ["Geography","What is the capital of Morocco?","Rabat"],
  ["Geography","In which country is Machu Picchu?","Peru"],
  ["Geography","What is the currency of South Korea?","won","South Korean won","Korean won"],
  ["Geography","Which country surrounds the independent city-state of San Marino?","Italy"],
  ["History","In what year was Magna Carta first issued?","1215","twelve fifteen"],
  ["History","What was Istanbul called when it was the capital of the Byzantine Empire?","Constantinople"],
  ["History","Which ancient Egyptian writing system did the Rosetta Stone help scholars decipher?","hieroglyphs","hieroglyphics","Egyptian hieroglyphs","Egyptian hieroglyphics"],
  ["History","Which French emperor was defeated at Waterloo in 1815?","Napoleon Bonaparte","Napoleon"],
  ["History","Which archduke's assassination in 1914 helped trigger World War I?","Franz Ferdinand","Archduke Franz Ferdinand"],
  ["History","Who developed movable metal type printing in Europe in the 15th century?","Johannes Gutenberg","Gutenberg"],
  ["History","Who was the first Roman emperor?","Augustus","Octavian","Caesar Augustus"],
  ["History","What knotted-cord system did the Inca use to record information?","quipu","khipu","quipus"],
  ["Science","Which chemical element has the symbol W?","tungsten","wolfram"],
  ["Science","What is the SI unit of force?","newton","newtons"],
  ["Science","Which cell organelles produce most ATP during aerobic respiration?","mitochondria","mitochondrion"],
  ["Science","Which gas makes up about 78 percent of Earth's atmosphere?","nitrogen","N2"],
  ["Science","At 25 degrees Celsius, what pH is neutral pure water?","7","seven"],
  ["Science","Which subatomic particle carries a negative electric charge?","electron","electrons"],
  ["Science","Atoms of the same element with different mass numbers differ in their number of which particles?","neutrons","neutron"],
  ["Science","What term describes light changing direction as it passes between materials?","refraction"],
  ["Books","Who wrote the novel Nineteen Eighty-Four?","George Orwell","Orwell"],
  ["Books","Who wrote Frankenstein?","Mary Shelley","Shelley"],
  ["Books","Who wrote The Hobbit?","J R R Tolkien","JRR Tolkien","Tolkien"],
  ["Books","Who wrote Pride and Prejudice?","Jane Austen","Austen"],
  ["Books","Who created the detective Sherlock Holmes?","Arthur Conan Doyle","Conan Doyle","Doyle","Sir Arthur Conan Doyle"],
  ["Books","Who wrote the novella The Metamorphosis?","Franz Kafka","Kafka"],
  ["Books","Which ancient Greek poet is traditionally credited with The Odyssey?","Homer"],
  ["Books","Who wrote One Hundred Years of Solitude?","Gabriel Garcia Marquez","Garcia Marquez","Marquez"],
  ["Movies","Who directed the 2010 film Inception?","Christopher Nolan","Nolan"],
  ["Movies","Who directed the 2019 film Parasite?","Bong Joon ho","Bong Joonho","Bong"],
  ["Movies","Who directed the animated film Spirited Away?","Hayao Miyazaki","Miyazaki"],
  ["Movies","What is the hacker alias of the main character played by Keanu Reeves in The Matrix?","Neo"],
  ["Movies","What car brand is used for the time machine in Back to the Future?","DeLorean","DMC","DeLorean DMC 12"],
  ["Movies","Which character calls the One Ring my precious in The Lord of the Rings films?","Gollum","Smeagol"],
  ["Movies","Who directed Pulp Fiction?","Quentin Tarantino","Tarantino"],
  ["Movies","What fictional African country is home to Marvel's Black Panther?","Wakanda"],
  ["Technology","In internet networking, what does DNS stand for?","Domain Name System"],
  ["Technology","Which HTTP status code means Not Found?","404","404 Not Found","four hundred four","four oh four"],
  ["Technology","Who created the Git version control system in 2005?","Linus Torvalds","Torvalds","Linus"],
  ["Technology","What is the name of the penguin mascot of Linux?","Tux"],
  ["Technology","Which data structure typically processes items first in, first out?","queue","a queue"],
  ["Technology","Which data structure typically processes items last in, first out?","stack","a stack"],
  ["Technology","What does SQL stand for?","Structured Query Language"],
  ["Technology","What decimal number is represented by the binary number 101101?","45","forty five"],
  ["Music","Who was Queen's lead vocalist on Bohemian Rhapsody?","Freddie Mercury","Mercury"],
  ["Music","Which French electronic duo released Random Access Memories in 2013?","Daft Punk"],
  ["Music","Which composer wrote The Four Seasons violin concertos?","Antonio Vivaldi","Vivaldi"],
  ["Music","Which numbered Beethoven symphony features the Ode to Joy choral finale?","9","ninth","9th","Symphony 9","Symphony No 9","nine"],
  ["Music","Which band released the 1969 album Abbey Road?","the Beatles","Beatles"],
  ["Music","Which rapper released To Pimp a Butterfly in 2015?","Kendrick Lamar","Kendrick","Lamar"],
  ["Music","Which band released OK Computer in 1997?","Radiohead"],
  ["Music","What is the relative minor key of C major?","A minor","Am"],
  ["Gaming","What is the full name of the bounty hunter protagonist in Metroid?","Samus Aran","Samus"],
  ["Gaming","What kingdom is the main setting of many Legend of Zelda games?","Hyrule","Kingdom of Hyrule"],
  ["Gaming","What is the name of the antagonistic AI in Portal?","GLaDOS"],
  ["Gaming","What is the name of the protagonist in Tomb Raider?","Lara Croft","Lara","Croft"],
  ["Gaming","Which Final Fantasy VII protagonist carries the Buster Sword?","Cloud Strife","Cloud"],
  ["Gaming","What fiery dimension can be reached through an obsidian portal in Minecraft?","Nether","the Nether"],
  ["Gaming","What pink Nintendo character inhales enemies and can copy their abilities?","Kirby"],
  ["Gaming","What is the name of the ruined underwater city in the original BioShock?","Rapture"],
  ["Motorsport","Which driver won the 2009 Formula 1 Drivers' Championship?","Jenson Button","Button"],
  ["Motorsport","Which driver won the 2007 Formula 1 Drivers' Championship?","Kimi Raikkonen","Raikkonen","Kimi"],
  ["Motorsport","Which driver won the 2010 Formula 1 Drivers' Championship?","Sebastian Vettel","Vettel"],
  ["Motorsport","Which team won the 2009 Formula 1 Constructors' Championship in its only season under that name?","Brawn GP","Brawn","Brawn Mercedes"],
  ["Motorsport","In which Brazilian city is the Interlagos Formula 1 circuit?","Sao Paulo"],
  ["Motorsport","What was Ayrton Senna's nationality?","Brazilian","Brazil"],
  ["Motorsport","Which French city gives its name to the famous 24-hour endurance race?","Le Mans"],
  ["Motorsport","In Formula 1's 2021 rules, what did DRS stand for?","Drag Reduction System"],
];

export const QUESTIONS = rows.map(([category, text, ...answers], index) => ({
  id: index + 1, category, text, answers, difficulty: 'medium',
}));

export function normalizeAnswer(value) {
  return String(value).normalize('NFKD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/[^a-z0-9]/g, '');
}

export function isCorrect(question, answer) {
  const normalized = normalizeAnswer(answer);
  return normalized.length > 0 && question.answers.some(value => normalizeAnswer(value) === normalized);
}
