// Original prompts using stable, basic facts. Keep answers on the server.
const rows = [
  ['Space', 'Which planet is known as the Red Planet?', 'Mars'],
  ['Geography', 'What is the capital of France?', 'Paris'],
  ['Science', 'What gas do plants absorb during photosynthesis?', 'carbon dioxide', 'CO2'],
  ['Numbers', 'What is 12 multiplied by 8?', '96', 'ninety six'],
  ['Animals', 'How many legs does a spider have?', '8', 'eight'],
  ['Food', 'What fruit is the main ingredient in guacamole?', 'avocado', 'avocados'],
  ['Music', 'How many strings does a standard guitar have?', '6', 'six'],
  ['Sport', 'How many players are on the field for one soccer team at kickoff?', '11', 'eleven'],
  ['Space', 'What star is at the center of our solar system?', 'Sun', 'the sun'],
  ['Geography', 'What is the capital of Japan?', 'Tokyo'],
  ['Science', 'What is the chemical symbol for gold?', 'Au'],
  ['Numbers', 'What is the square root of 144?', '12', 'twelve'],
  ['Animals', 'What is the largest living land animal?', 'African elephant', 'elephant', 'African bush elephant'],
  ['Food', 'What ingredient makes bread dough rise through fermentation?', 'yeast'],
  ['Music', 'What instrument has black and white keys and strings struck by hammers?', 'piano'],
  ['Sport', 'What sport uses a shuttlecock?', 'badminton'],
  ['Space', 'Which planet has the largest diameter in our solar system?', 'Jupiter'],
  ['Geography', 'Which ocean is the largest?', 'Pacific', 'Pacific Ocean'],
  ['Science', 'What is H2O commonly called?', 'water'],
  ['Numbers', 'How many sides does a hexagon have?', '6', 'six'],
  ['Animals', 'What is a baby frog called?', 'tadpole'],
  ['Food', 'What grain is traditionally used to make risotto?', 'rice'],
  ['Music', 'How many semitones make an octave?', '12', 'twelve'],
  ['Sport', 'In tennis, what word means a score of zero?', 'love'],
  ['Space', 'Which planet is closest to the Sun?', 'Mercury'],
  ['Geography', 'What is the capital of Italy?', 'Rome'],
  ['Science', 'What force pulls objects toward Earth?', 'gravity', 'gravitation'],
  ['Numbers', 'What is 25 percent of 200?', '50', 'fifty'],
  ['Animals', 'What black-and-white bear is native to China?', 'giant panda', 'panda'],
  ['Food', 'What bean is used to make tofu?', 'soybean', 'soybeans', 'soy', 'soya'],
  ['Music', 'What instrument is commonly played with a bow and held under the chin?', 'violin', 'fiddle'],
  ['Sport', 'How many rings are in the Olympic symbol?', '5', 'five'],
  ['Space', 'What is Earth’s natural satellite called?', 'Moon', 'the moon'],
  ['Geography', 'What is the capital of Spain?', 'Madrid'],
  ['Science', 'What organ pumps blood around the human body?', 'heart', 'the heart'],
  ['Numbers', 'What is 9 squared?', '81', 'eighty one'],
  ['Animals', 'What is a group of wolves commonly called?', 'pack', 'a pack'],
  ['Food', 'What fruit is dried to make raisins?', 'grape', 'grapes'],
  ['Music', 'What instrument usually has six strings and is strummed?', 'guitar'],
  ['Sport', 'In golf, what is one stroke under par called?', 'birdie', 'a birdie'],
  ['Space', 'Which planet is famous for its large, visible ring system?', 'Saturn'],
  ['Geography', 'What is the capital of Germany?', 'Berlin'],
  ['Science', 'At standard atmospheric pressure, at what Celsius temperature does water freeze?', '0', 'zero', '0 degrees'],
  ['Numbers', 'How many degrees are in a right angle?', '90', 'ninety'],
  ['Animals', 'What tall animal has a very long neck?', 'giraffe'],
  ['Food', 'What spice gives many curries a bright yellow color?', 'turmeric'],
  ['Music', 'What does a musical rest tell a musician to do?', 'pause', 'be silent', 'silence', 'stop playing'],
  ['Sport', 'How many points is a free throw worth in basketball?', '1', 'one'],
  ['Space', 'How many planets are in our solar system?', '8', 'eight'],
  ['Geography', 'What is the capital of Canada?', 'Ottawa'],
  ['Science', 'What is the chemical symbol for oxygen?', 'O'],
  ['Numbers', 'What is 7 multiplied by 9?', '63', 'sixty three'],
  ['Animals', 'What insect makes honey?', 'bee', 'bees', 'honeybee', 'honey bee'],
  ['Food', 'What is the main ingredient in hummus?', 'chickpea', 'chickpeas', 'garbanzo beans'],
  ['Music', 'What is the name for the speed of a piece of music?', 'tempo'],
  ['Sport', 'What sport is played at Wimbledon?', 'tennis'],
  ['Space', 'What galaxy contains our solar system?', 'Milky Way', 'the milky way'],
  ['Geography', 'What is the capital of Australia?', 'Canberra'],
  ['Science', 'What is the chemical symbol for iron?', 'Fe'],
  ['Numbers', 'How many sides does an octagon have?', '8', 'eight'],
  ['Animals', 'What mammal is capable of sustained powered flight?', 'bat', 'bats'],
  ['Food', 'What Italian dish has layers of pasta and sauce?', 'lasagna', 'lasagne'],
  ['Music', 'What symbol raises a note by one semitone?', 'sharp', 'a sharp'],
  ['Sport', 'In baseball, how many strikes normally make an out?', '3', 'three'],
  ['Space', 'Which planet is second from the Sun?', 'Venus'],
  ['Geography', 'What is the capital of Egypt?', 'Cairo'],
  ['Science', 'What is the chemical symbol for carbon?', 'C'],
  ['Numbers', 'What is 15 multiplied by 4?', '60', 'sixty'],
  ['Animals', 'What sea animal has eight arms?', 'octopus', 'an octopus'],
  ['Food', 'What dairy product is churned from cream?', 'butter'],
  ['Music', 'What symbol lowers a note by one semitone?', 'flat', 'a flat'],
  ['Sport', 'What sport uses a puck on ice?', 'ice hockey', 'hockey'],
  ['Space', 'What is the name of the first human to walk on the Moon?', 'Neil Armstrong', 'Armstrong'],
  ['Geography', 'What is the capital of Portugal?', 'Lisbon'],
  ['Science', 'What is the hardest mineral on the Mohs scale?', 'diamond'],
  ['Numbers', 'How many minutes are in two and a half hours?', '150', 'one hundred fifty', 'one hundred and fifty'],
  ['Animals', 'What is a baby dog called?', 'puppy', 'a puppy'],
  ['Food', 'What vegetable is the main ingredient in sauerkraut?', 'cabbage'],
  ['Music', 'What is the highest common adult female singing voice?', 'soprano'],
  ['Sport', 'How many points is a basketball shot from beyond the three-point line worth?', '3', 'three'],
  ['Space', 'What planet do we live on?', 'Earth'],
  ['Geography', 'What is the capital of Greece?', 'Athens'],
  ['Science', 'What organ do humans primarily use to breathe?', 'lungs', 'lung'],
  ['Numbers', 'What is 1000 divided by 25?', '40', 'forty'],
  ['Animals', 'What is a baby cat called?', 'kitten', 'a kitten'],
  ['Food', 'What fruit is used in traditional lemonade?', 'lemon', 'lemons'],
  ['Music', 'What is the lowest common adult male singing voice?', 'bass'],
  ['Sport', 'What sport uses clubs to hit a ball into holes?', 'golf'],
  ['Geography', 'What is the capital of Ireland?', 'Dublin'],
  ['Numbers', 'How many sides does a pentagon have?', '5', 'five'],
  ['Science', 'What unit measures electrical resistance?', 'ohm', 'ohms'],
  ['Animals', 'What animal is known for a black-and-white striped coat?', 'zebra'],
  ['Food', 'What nut is used in traditional marzipan?', 'almond', 'almonds'],
  ['Numbers', 'What is 11 multiplied by 11?', '121', 'one hundred twenty one', 'one hundred and twenty one'],
  ['Geography', 'What is the capital of Norway?', 'Oslo'],
  ['Science', 'What process turns liquid water into water vapor?', 'evaporation'],
];

export const QUESTIONS = rows.map(([category, text, ...answers], index) => ({ id: index + 1, category, text, answers }));

export function normalizeAnswer(value) {
  return String(value).normalize('NFKD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/[^a-z0-9]/g, '');
}

export function isCorrect(question, answer) {
  const normalized = normalizeAnswer(answer);
  return normalized.length > 0 && question.answers.some(value => normalizeAnswer(value) === normalized);
}
